sudo: false
language: node_js
env:
  - CXX="g++-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
  - "8"
  - "6"
  - "4"
before_script:
  - npm install -g istanbul grunt-cli
  - npm install coveralls
  - npm install node-red
script:
  - istanbul cover grunt --report lcovonly && istanbul report text && ( cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true ) && rm -rf coverage
